using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Bespoke_app_server.Migrations
{
    /// <inheritdoc />
    /// <remarks>
    /// Idempotent: <c>SubscriptionOwnerships</c> may already exist in Supabase. Creates table/indexes only when missing.
    /// </remarks>
    public partial class MapSubscriptionOwnerships : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS "SubscriptionOwnerships" (
                    "SubscriptionOwnershipId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "OriginalTransactionId" character varying(128) NOT NULL,
                    "ProductId" character varying(256) NOT NULL,
                    "UserId" integer NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    CONSTRAINT "FK_SubscriptionOwnerships_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE CASCADE
                );

                CREATE UNIQUE INDEX IF NOT EXISTS "IX_SubscriptionOwnerships_OriginalTransactionId"
                    ON "SubscriptionOwnerships" ("OriginalTransactionId");

                CREATE INDEX IF NOT EXISTS "IX_SubscriptionOwnerships_UserId"
                    ON "SubscriptionOwnerships" ("UserId");
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""DROP TABLE IF EXISTS "SubscriptionOwnerships" CASCADE;""");
        }
    }
}
