// <auto-generated />
using System;
using BespokeDuaApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bespoke_app_server.Migrations
{
    [DbContext(typeof(BespokeDuaDbContext))]
    [Migration("20260706015651_AddSunnahDuasToCollections")]
    partial class AddSunnahDuasToCollections
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BespokeDuaApi.Models.AllahName", b =>
                {
                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("Arabic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("FeelingLabelId")
                        .HasColumnType("integer");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Transliteration")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Number");

                    b.HasIndex("FeelingLabelId", "SortOrder");

                    b.ToTable("AllahNames");
                });

            modelBuilder.Entity("BespokeDuaApi.Models.DuaCollection", b =>
                {
                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("CollectionId");

                    b.HasIndex("UserId");

                    b.ToTable("DuaCollections");
                });

            modelBuilder.Entity("BespokeDuaApi.Models.DuaCollectionItem", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DuaId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SunnahDuaId")
                        .HasColumnType("uuid");

                    b.HasKey("ItemId");

                    b.HasIndex("DuaId");

                    b.HasIndex("SunnahDuaId");

                    b.HasIndex("CollectionId", "DuaId")
                        .IsUnique()
                        .HasFilter("\"DuaId\" IS NOT NULL");

                    b.HasIndex("CollectionId", "SunnahDuaId")
                        .IsUnique()
                        .HasFilter("\"SunnahDuaId\" IS NOT NULL");

                    b.ToTable("DuaCollectionItems");
                });

            modelBuilder.Entity("BespokeDuaApi.Models.FeelingLabel", b =>
                {
                    b.Property<int>("FeelingLabelId")
                        .HasColumnType("integer");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("FeelingLabelId");

                    b.HasIndex("Label")
                        .IsUnique();

                    b.ToTable("FeelingLabels");
                });

            modelBuilder.Entity("BespokeDuaApi.Models.SavedDua", b =>
                {
                    b.Property<Guid>("DuaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Dua")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("DuaId");

                    b.HasIndex("UserId");

                    b.ToTable("SavedDuas");
                });

            modelBuilder.Entity("BespokeDuaApi.Models.SavedSunnahDua", b =>
                {
                    b.Property<Guid>("SunnahDuaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SunnahDua")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("SunnahDuaId");

                    b.HasIndex("UserId");

                    b.ToTable("SavedSunnahDuas");
                });

            modelBuilder.Entity("BespokeDuaApi.Models.SubscriptionOwnership", b =>
                {
                    b.Property<int>("SubscriptionOwnershipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubscriptionOwnershipId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OriginalTransactionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("SubscriptionOwnershipId");

                    b.HasIndex("OriginalTransactionId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("SubscriptionOwnerships", (string)null);
                });

            modelBuilder.Entity("BespokeDuaApi.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<Guid?>("AuthUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DailyRequests")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("HashedPassword")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastRequestDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MonthlyRequests")
                        .HasColumnType("integer");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("UserId");

                    b.HasIndex("AuthUserId")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BespokeDuaApi.Models.UserUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<int>("RequestsCount")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date")
                        .IsUnique();

                    b.ToTable("UserUsages");
                });

            modelBuilder.Entity("BespokeDuaApi.Models.AllahName", b =>
                {
                    b.HasOne("BespokeDuaApi.Models.FeelingLabel", "FeelingLabel")
                        .WithMany("Names")
                        .HasForeignKey("FeelingLabelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FeelingLabel");
                });

            modelBuilder.Entity("BespokeDuaApi.Models.DuaCollection", b =>
                {
                    b.HasOne("BespokeDuaApi.Models.User", "User")
                        .WithMany("DuaCollections")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BespokeDuaApi.Models.DuaCollectionItem", b =>
                {
                    b.HasOne("BespokeDuaApi.Models.DuaCollection", "Collection")
                        .WithMany("Items")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BespokeDuaApi.Models.SavedDua", "SavedDua")
                        .WithMany("CollectionItems")
                        .HasForeignKey("DuaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BespokeDuaApi.Models.SavedSunnahDua", "SavedSunnahDua")
                        .WithMany("CollectionItems")
                        .HasForeignKey("SunnahDuaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Collection");

                    b.Navigation("SavedDua");

                    b.Navigation("SavedSunnahDua");
                });

            modelBuilder.Entity("BespokeDuaApi.Models.SavedDua", b =>
                {
                    b.HasOne("BespokeDuaApi.Models.User", "User")
                        .WithMany("SavedDuas")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BespokeDuaApi.Models.SavedSunnahDua", b =>
                {
                    b.HasOne("BespokeDuaApi.Models.User", "User")
                        .WithMany("SavedSunnahDuas")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BespokeDuaApi.Models.SubscriptionOwnership", b =>
                {
                    b.HasOne("BespokeDuaApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BespokeDuaApi.Models.UserUsage", b =>
                {
                    b.HasOne("BespokeDuaApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BespokeDuaApi.Models.DuaCollection", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("BespokeDuaApi.Models.FeelingLabel", b =>
                {
                    b.Navigation("Names");
                });

            modelBuilder.Entity("BespokeDuaApi.Models.SavedDua", b =>
                {
                    b.Navigation("CollectionItems");
                });

            modelBuilder.Entity("BespokeDuaApi.Models.SavedSunnahDua", b =>
                {
                    b.Navigation("CollectionItems");
                });

            modelBuilder.Entity("BespokeDuaApi.Models.User", b =>
                {
                    b.Navigation("DuaCollections");

                    b.Navigation("SavedDuas");

                    b.Navigation("SavedSunnahDuas");
                });
#pragma warning restore 612, 618
        }
    }
}
